name: Ошибка / Bug report
description: Сообщить об ошибке
body:
  - type: textarea
    id: problem
    attributes:
      label: Что произошло и как повторить?
      description: Не прикладывайте личные данные или секреты.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Версия Wisp
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Версии игры/API, ОС, режим сохранения и другие моды
