blank_issues_enabled: false
contact_links:
  - name: Вопросы и идеи / Discussions
    url: https://github.com/Alexandr-Fredrix/Wisp/discussions
    about: Обсудить мод, задать вопрос или предложить улучшение.
